SELECT PRJ.IDENTIFICACAO PROCESSO
		,UPPER(PRO.AD_CULTIVAR) AS TIPOPROD
		,TOP.CODTIPOPER  
		,TOP.DESCROPER
		,(CASE WHEN CAB.TIPMOV = 'D' THEN 'DEVOLUCAO'
		      WHEN CAB.TIPMOV = 'V' AND TOP.DESCROPER LIKE '%TRANSF%' THEN 'TRANSFERENCIA'
		      WHEN CAB.TIPMOV = 'V' AND TOP.DESCROPER LIKE '%REFUG%' THEN 'REFUGO'
		      WHEN CAB.TIPMOV = 'V' AND TOP.DESCROPER LIKE '%VENDA%' THEN 'VENDA'
		      WHEN CAB.TIPMOV = 'V' AND TOP.DESCROPER LIKE '%COMPLE%' THEN 'COMPLEMENTAR'
		      WHEN CAB.TIPMOV = 'V' AND TOP.DESCROPER LIKE '%DESIDR%' THEN 'REMESSA'
		      ELSE 'OUTROS' END) OPERACAO
		,CAB.TIPMOV 
		,UPPER(TOP.GRUPO) GRUPOTOP
		,PAR.CODPARC ||'-'||PAR.NOMEPARC PARCEIRO
		,CAB.DTNEG 
		,CAB.DTENTSAI DATASAIDA
		,CAB.NUNOTA
		,CAB.NUMNOTA NUMERONF
		,CAB.NUMPEDIDO2 AS PO
		,CAB.SERIENOTA 
        ,CAB.codemp
		,CAB.AD_EX_CONTAINER 
		,NAV.AD_NAVIO AS VESSEL 
		,CAB.AD_LINER AS SHIPPINGLINE
		,CAB.AD_EX_DTPREVEMB ETD
		,CAB.AD_EX_DTPREVDES ETA 
		,PO1.NOMPORTO PORTO_ORIGEM
		,PO2.NOMPORTO PORTO_DESTINO
		,CAB.CANCELADO 
		,CAB.CHAVENFE 
		,F_DESCROPC('TGFCAB','AD_INCOTERM',CAB.AD_INCOTERM ) INCONTERMS 
	    ,CAB.AD_EX_TERMOG 
	    ,F_DESCROPC('TGFCAB', 'AD_MODELO', CAB.AD_MODELO) MODTERMOGRAFO
	    ,CAB.AD_PALLET AS PALLET_TERM
	    ,CASE WHEN UFS.CODPAIS=55 THEN 'MI' ELSE 'ME' END AS MERCADO
        ,ITE.SEQUENCIA 
	    ,PRO.CODPROD||'-'||PRO.DESCRPROD PRODUTO
        ,PRO.AD_CULTIVAR 
        ,PRO.CODVOL
        ,PRO.MARCA
        ,PAL_CODLOCAL
        ,PAL_DESCRLOCAL
        ,MOE.NOMEMOEDA
        ,PRO.PESOBRUTO
        ,(ITE.QTDNEG * PRO.PESOBRUTO) PESOBRUTOTOTAL
        ,PRO.PESOLIQ
        ,(ITE.QTDNEG * PRO.PESOLIQ) PESOLIQDOTOTAL
        ,ITE.QTDNEG 
	    ,ite.CONTROLE
	    ,ite.AD_PALLET
	    ,ITE.VLRUNIT
	    ,ITE.VLRTOT 
	    ,PRO.USOPROD
	    ,PRD.PAL_OBSQUALIDADE
		,PRD.GGN
	    ,PRD.PAL_CODSTATUS
	    ,PRD.PAL_DESCBLQ
	    ,UPPER(CID.NOMECID) CIDADE
	    ,UPPER(UFS.DESCRICAO) ESTADO
	    ,UPPER(PAI.DESCRICAO) PAIS
	    ,COALESCE(MP.PROD,GRU.AD_DESCRESUMO) VARIEDADE
	    ,GRU.DESCRGRUPOPROD GRUPO_PROD
	    ,CAB.STATUSNFE 
	    ,PRD.PRODUTOR PRODUTOR
	    ,PRD.DESCRICAO
	    --,ACM.NUNOTA 
        ,COALESCE(PRD.QTDE_PRODUTOR,TO_CHAR(ITE.QTDNEG)) QTDE_PRODUTOR
        ,nvl(PRD.LOTE,(SELECT LISTAGG(DISTINCT AR.ARG_LOTE,',') FROM AD_ROMANEIOENTR AR WHERE AR.CODPROD=ITE.CODPROD AND TO_CHAR(AR.ROMANEIO)=TO_CHAR(ITE.CONTROLE)) ) AS LOTE
        ,PRD.ROMANEIO
        ,CAB.VLRMOEDA
        ,ITE.VLRUNITMOE
        ,(trunc(CAB.DTENTSAI) - PRD.PAL_DTFABRICACAO) AS MEDIA_DIA
        ,to_char ((CAB.DTENTSAI),'WW') packingweek
        ,COALESCE(PRD.CUSTOKG,(SELECT  AVG(ACM.VLRUNIT)  FROM ARG_COMPRA_MP ACM WHERE ACM.CODPROD=ITE.CODPROD AND ACM.CONTROLE=ITE.CONTROLE AND ACM.CLASS_CALIBRE=ITE.AD_CALIBRE AND ITE.AD_PALLET IS NULL)) AS CUSTOKG
        -- GLPI 1812: romaneio de entrada, producao e colheita mais antiga do pallet.
        -- Colheita = mesma regra do DT_COLHEITA_MIN da view AD_ESTPALLET (dash 208): PIT.LOTE = NROUNICO do romaneio.
        -- Item sem pallet: o CONTROLE do item e o numero do romaneio.
        ,NVL((SELECT LISTAGG(DISTINCT TO_CHAR(AR.ROMANEIO), ',') WITHIN GROUP (ORDER BY TO_CHAR(AR.ROMANEIO))
                FROM AD_MONTPALLETITE PIT JOIN AD_ROMANEIOENTR AR ON AR.NROUNICO = PIT.LOTE
               WHERE PIT.NROUNICO = ITE.AD_PALLET), ITE.CONTROLE) AS ROMANEIO_ENT
        ,PRD.PAL_DTFABRICACAO AS DT_PRODUCAO
        ,CASE WHEN ITE.AD_PALLET IS NOT NULL
              THEN (SELECT MIN(AR.DTCOLHEITA) FROM AD_MONTPALLETITE PIT JOIN AD_ROMANEIOENTR AR ON AR.NROUNICO = PIT.LOTE WHERE PIT.NROUNICO = ITE.AD_PALLET)
              ELSE (SELECT MIN(AR.DTCOLHEITA) FROM AD_ROMANEIOENTR AR WHERE AR.CODPROD = ITE.CODPROD AND TO_CHAR(AR.ROMANEIO) = TO_CHAR(ITE.CONTROLE))
         END AS DT_MIN_COLHEITA
        ,TRUNC(CAB.DTENTSAI) -
         CASE WHEN ITE.AD_PALLET IS NOT NULL
              THEN (SELECT MIN(AR.DTCOLHEITA) FROM AD_MONTPALLETITE PIT JOIN AD_ROMANEIOENTR AR ON AR.NROUNICO = PIT.LOTE WHERE PIT.NROUNICO = ITE.AD_PALLET)
              ELSE (SELECT MIN(AR.DTCOLHEITA) FROM AD_ROMANEIOENTR AR WHERE AR.CODPROD = ITE.CODPROD AND TO_CHAR(AR.ROMANEIO) = TO_CHAR(ITE.CONTROLE))
         END AS QT_DIAS_COLHEITA
        
FROM  TGFCAB CAB   
 JOIN TGFITE ITE   ON (CAB.NUNOTA=ITE.NUNOTA)
 JOIN TGFPRO PRO   ON (ITE.CODPROD=PRO.CODPROD)
 JOIN TGFPAR PAR   ON (PAR.CODPARC=CAB.CODPARC)
 JOIN TCSPRJ PRJ   ON (PRJ.CODPROJ=CAB.CODPROJ)
 JOIN TGFTOP TOP   ON (TOP.CODTIPOPER=CAB.CODTIPOPER AND CAB.DHTIPOPER = TOP.DHALTER )
 JOIN TSICID CID ON (CID.CODCID=PAR.CODCID )
 JOIN TSIUFS UFS ON (UFS.CODUF=CID.UF)
 JOIN TSIPAI PAI ON (PAI.CODPAIS=UFS.CODPAIS)  
 JOIN TGFGRU GRU ON (PRO.CODGRUPOPROD  = GRU.CODGRUPOPROD) 
 LEFT JOIN TSIMOE MOE   ON (MOE.CODMOEDA=CAB.CODMOEDA)
 LEFT JOIN AD_PORTO PO1 ON (PO1.IDPORTO=CAB.AD_EX_PORTOEMBARQUE)
 LEFT JOIN AD_PORTO PO2 ON (PO2.IDPORTO=CAB.AD_EX_PORTODESCARGA) 
 LEFT JOIN TGFVEI NAV   ON (NAV.CODVEICULO=CAB.AD_EX_NAVIO)
 LEFT JOIN AD_FRUTA AF ON UPPER(AF.NOME) = UPPER(PRO.AD_CULTIVAR)
 LEFT JOIN (SELECT listagg(DISTINCT P1.DESCRPROD,',') PROD,af.CODPROD  
            FROM AD_FICHATECPROD af
                 JOIN TGFPRO P1 ON af.CODPRODMP =P1.CODPROD GROUP BY af.CODPROD) MP ON MP.CODPROD=ITE.CODPROD
 LEFT JOIN (SELECT  listagg(SUBSTR(am.PITE_CODPRODUTOR ||' - '||am.PITE_PAR_NOMEPARC,0,20) ,',') PRODUTOR
                    ,listagg(am.PITE_QTD  ,' , ') QTDE_PRODUTOR 
                    ,listagg(am.PITE_LOTEARGO,' , ') LOTE
                    ,listagg(am.PITE_LOTE,',') ROMANEIO
                    ,listagg(am.PITE_NUMCERTIFICADO ,' , ') GGN
                    ,listagg(am.PITE_CALIBRE  ,' , ') CALIBRE
                    ,listagg(am.CB_DESCRICAO  ,' , ') DESCRICAO
                    ,am.PAL_NROUNICO NROUNICO
                    ,am.PAL_OBSQUALIDADE
                    ,am.PAL_DESCBLQ
                    ,am.PAL_CODSTATUS
                    ,am.PAL_CODLOCAL
                    ,am.PAL_DESCRLOCAL
                    ,am.PAL_DTFABRICACAO
                    ,AVG(am.MED_CUST_LT) CUSTOKG
            FROM VW_ARG_DETALHA_PALLET am 
			GROUP BY am.PAL_NROUNICO,am.PAL_OBSQUALIDADE,am.PAL_DTFABRICACAO, am.PAL_DESCBLQ, am.PAL_CODLOCAL, am.PAL_DESCRLOCAL, am.PAL_CODSTATUS) PRD ON PRD.NROUNICO=ITE.AD_PALLET
             
-- LEFT JOIN (SELECT AD_ROMANEIOENTR AR ON AR.CODPROD=ITE.CODPROD AND TO_CHAR(AR.ROMANEIO)=TO_CHAR(ITE.CONTROLE)  
WHERE CAB.STATUSNOTA = 'L' 
  --AND TOP.GRUPO ='Vendas'
  AND PRO.USOPROD IN ('T','R','V','M')
  AND UPPER(TOP.GRUPO) NOT IN ('AJUSTES')
  AND CAB.TIPMOV  IN ('D','V') 
  AND DTENTSAI  BETWEEN TO_DATE('22/09/2026','DD/MM/YYYY') AND TO_DATE('23/09/2026','DD/MM/YYYY') 
  AND (1=1)
  AND (CASE WHEN UFS.CODPAIS=55 THEN 'MI' ELSE 'ME' END) IN ('ME','MI') 
  AND (CASE WHEN CAB.TIPMOV = 'D' THEN 'DEVOLUCAO'
		      WHEN CAB.TIPMOV = 'V' AND TOP.DESCROPER LIKE '%TRANSF%' THEN 'TRANSFERENCIA'
		      WHEN CAB.TIPMOV = 'V' AND TOP.DESCROPER LIKE '%REFUG%' THEN 'REFUGO'
		      WHEN CAB.TIPMOV = 'V' AND TOP.DESCROPER LIKE '%VENDA%' THEN 'VENDA'
		      WHEN CAB.TIPMOV = 'V' AND TOP.DESCROPER LIKE '%COMPLE%' THEN 'COMPLEMENTAR'
		      WHEN CAB.TIPMOV = 'V' AND TOP.DESCROPER LIKE '%DESIDR%' THEN 'REMESSA'
		      ELSE 'OUTROS' END) IN ('VENDA','DEVOLUCAO','TRANSFERENCIA','REFUGO','COMPLEMENTAR','REMESSA','OUTROS')