-- GLPI 1812 - testes das colunas novas do dash 94 (Portal de Vendas) no DbExplorer
-- ROMANEIO_ENT, DT_PRODUCAO, DT_MIN_COLHEITA, QT_DIAS_COLHEITA
-- Regra da colheita = grade de detalhe do pallet no dash 208 (ESTOQUE DE PALLETS P/ MARCACAO):
--   por item do pallet, MAX(ARG_COMPRA_MP.DTCOLHEITA) por romaneio + produtor + calibre;
--   no pallet, a mais antiga entre os itens. Dias = data de saida da nota - colheita.


-- TESTE 1: colunas novas numa nota da print do chamado (NF 134295, pallets 0330/0334/0352/0372-272612)
SELECT CAB.NUMNOTA, CAB.DTENTSAI, ITE.SEQUENCIA, ITE.AD_PALLET, ITE.CONTROLE
      ,NVL(CPL.ROMANEIO_ENT, ITE.CONTROLE) AS ROMANEIO_ENT
      ,(SELECT MAX(V.PAL_DTFABRICACAO) FROM VW_ARG_DETALHA_PALLET V WHERE V.PAL_NROUNICO = ITE.AD_PALLET) AS DT_PRODUCAO
      ,NVL(CPL.DT_MIN_COLHEITA, CDI.DT_MIN_COLHEITA) AS DT_MIN_COLHEITA
      ,TRUNC(CAB.DTENTSAI) - NVL(CPL.DT_MIN_COLHEITA, CDI.DT_MIN_COLHEITA) AS QT_DIAS_COLHEITA
FROM TGFCAB CAB
JOIN TGFITE ITE ON ITE.NUNOTA = CAB.NUNOTA
OUTER APPLY (SELECT LISTAGG(DISTINCT TO_CHAR(X.LOTE), ',') WITHIN GROUP (ORDER BY TO_CHAR(X.LOTE)) ROMANEIO_ENT
                   ,TRUNC(MIN(X.DTCOLHEITA)) DT_MIN_COLHEITA
             FROM (SELECT PIT.LOTE
                         ,(SELECT MAX(CMP.DTCOLHEITA)
                             FROM ARG_COMPRA_MP CMP
                            WHERE CMP.NRROMANEIO_ENT = PIT.LOTE
                              AND CMP.CODPARC        = PIT.CODPRODUTOR
                              AND CMP.CLASS_CALIBRE  = PIT.CALIBRE) DTCOLHEITA
                     FROM AD_MONTPALLETITE PIT
                    WHERE PIT.NROUNICO = ITE.AD_PALLET) X) CPL
OUTER APPLY (SELECT TRUNC(MIN(CMP.DTCOLHEITA)) DT_MIN_COLHEITA
             FROM ARG_COMPRA_MP CMP
            WHERE ITE.AD_PALLET IS NULL
              AND CMP.CODPROD  = ITE.CODPROD
              AND CMP.CONTROLE = ITE.CONTROLE) CDI
WHERE CAB.NUMNOTA = 134295
  AND CAB.TIPMOV = 'V'
ORDER BY ITE.SEQUENCIA;


-- TESTE 2: conferencia item a item de 1 pallet (troque o NROUNICO por um AD_PALLET do teste 1).
-- A menor DATA_COLHEITA aqui tem que ser a DT_MIN_COLHEITA do teste 1,
-- e bate com a grade de detalhe do pallet no dash 208.
SELECT PIT.NROUNICO, PIT.LOTE ROMANEIO, PIT.CODPRODUTOR, PIT.CALIBRE, PIT.QTD
      ,(SELECT MAX(CMP.DTCOLHEITA)
          FROM ARG_COMPRA_MP CMP
         WHERE CMP.NRROMANEIO_ENT = PIT.LOTE
           AND CMP.CODPARC        = PIT.CODPRODUTOR
           AND CMP.CLASS_CALIBRE  = PIT.CALIBRE) AS DATA_COLHEITA
FROM AD_MONTPALLETITE PIT
WHERE PIT.NROUNICO = :NROUNICO
ORDER BY DATA_COLHEITA;


-- TESTE 3: cobertura num periodo (vendas ME) - quantos itens ficam sem colheita, com e sem pallet
SELECT CASE WHEN ITE.AD_PALLET IS NULL THEN 'SEM PALLET' ELSE 'COM PALLET' END TIPO
      ,COUNT(*) ITENS
      ,SUM(CASE WHEN NVL(CPL.DT_MIN_COLHEITA, CDI.DT_MIN_COLHEITA) IS NULL THEN 1 ELSE 0 END) SEM_COLHEITA
      ,MIN(TRUNC(CAB.DTENTSAI) - NVL(CPL.DT_MIN_COLHEITA, CDI.DT_MIN_COLHEITA)) MIN_DIAS
      ,MAX(TRUNC(CAB.DTENTSAI) - NVL(CPL.DT_MIN_COLHEITA, CDI.DT_MIN_COLHEITA)) MAX_DIAS
FROM TGFCAB CAB
JOIN TGFITE ITE ON ITE.NUNOTA = CAB.NUNOTA
JOIN TGFTOP TOP ON TOP.CODTIPOPER = CAB.CODTIPOPER AND TOP.DHALTER = CAB.DHTIPOPER
OUTER APPLY (SELECT TRUNC(MIN(X.DTCOLHEITA)) DT_MIN_COLHEITA
             FROM (SELECT (SELECT MAX(CMP.DTCOLHEITA)
                             FROM ARG_COMPRA_MP CMP
                            WHERE CMP.NRROMANEIO_ENT = PIT.LOTE
                              AND CMP.CODPARC        = PIT.CODPRODUTOR
                              AND CMP.CLASS_CALIBRE  = PIT.CALIBRE) DTCOLHEITA
                     FROM AD_MONTPALLETITE PIT
                    WHERE PIT.NROUNICO = ITE.AD_PALLET) X) CPL
OUTER APPLY (SELECT TRUNC(MIN(CMP.DTCOLHEITA)) DT_MIN_COLHEITA
             FROM ARG_COMPRA_MP CMP
            WHERE ITE.AD_PALLET IS NULL
              AND CMP.CODPROD  = ITE.CODPROD
              AND CMP.CONTROLE = ITE.CONTROLE) CDI
WHERE CAB.STATUSNOTA = 'L'
  AND CAB.TIPMOV = 'V'
  AND TOP.DESCROPER LIKE '%VENDA%'
  AND CAB.DTENTSAI BETWEEN TO_DATE('01/09/2026','DD/MM/YYYY') AND TO_DATE('28/09/2026','DD/MM/YYYY')
GROUP BY CASE WHEN ITE.AD_PALLET IS NULL THEN 'SEM PALLET' ELSE 'COM PALLET' END;


-- EXTRA: de onde a AD_ESTPALLET tira o DT_COLHEITA_MIN (para confirmar que a regra e a mesma)
SELECT NAME, TYPE, LINE, TEXT
FROM USER_SOURCE
WHERE UPPER(TEXT) LIKE '%DT_COLHEITA_MIN%' OR UPPER(TEXT) LIKE '%QT_DIAS_COLHEITA%'
ORDER BY NAME, LINE;
